// Generated by Wrangler on Sun Sep 15 2024 21:55:26 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	OPENAI_API_KEY: string;
	COGNITO_USER_POOL_ID: string;
	COGNITO_REGION: string;
	COGNITO_CLIENT_ID: string;
	CACHE: DurableObjectNamespace /* DurableObjectRateLimiter */;
}
