// Generated by Wrangler on Thu Sep 26 2024 20:31:58 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	OPENAI_API_KEY: string;
	COGNITO_USER_POOL_ID: string;
	COGNITO_REGION: string;
	COGNITO_CLIENT_ID: string;
}
